### ISSUE TITLE
Spam submission protection

### ISSUE THREAD

**Issue by wpsumo** [geminilabs/site-reviews#36]
Add similar spam protection as https://wordpress.org/plugins/forget-spam-comment/ built into site reviews.

Blacklists is too static and you either have to manually create yours adding words all the time that fits the need or use a one size fits all list which could block words which you don't want to block. But they are in these lists as they tend to be in spam. Cleaning such big lists would also be a lot of manual work https://github.com/splorp/wordpress-comment-blacklist

reCAPTCHA is one solution but not a favour of these external scripts, and maybe not all prefer reCAPTCHA. Above light JavaScript solution, would be a very simple but protective solution and lightweight. It would also be plug and play no external API keys needs to setup etc for users. Just enable the function in the plugin settings page. The explanation of the function of the plugin is within the plugin and the video on the plugin description page.

**Comment by pryley** [comment]
The problem with [forget-spam-comment/](https://wordpress.org/plugins/forget-spam-comment/) is that it depends on a page scroll to work. This works for comments because they are usually loaded at the end of the page. But this wouldn't work for sites that use a specific page to submit a review, and where the browser window is large enough that there is no page overflow for a scroll. For that reason, I probably won't implement this.

**Comment by wpsumo** [comment]
That is true and it's a valid point. This is just for inspirational purpose, you don't think you could come up with something smart for both edge cases? Like delaying JavaScript (https://wordpress.org/plugins/flying-scripts/) is working with a time-out if no user interaction happened, scroll click etc it loads after 5 seconds or 10 or 15 depending on what the user define to be time out. 

Wouldn't it work to fire the event to once the user hit submission button with an actual click event, or it will not prevent the spam bots then? Once you hit the submission it fires the action event which then send the submission the action which is now loaded and working. So instead of scroll it happens here.

Otherwise, a semi option to allow us via a filter or action to enable spam comment protection like forget comment spam (https://wordpress.org/plugins/forget-spam-comment/) where the ones who use is know it requires scroll and the ones that have the submission outside the viewport can use it. Not sure if the forget comments spam is built for scroll only or if it supports mobile touch wheel as well.

**Comment by wpsumo** [comment]
@pryley Did you see my comment above? What action do site reviews use to submit reviews? Does it use the wp-comments-post.php?

If there is a URL we can use we could use Cloudflare to block or challenge. But would also like to find a solution directly to prevent the spam without any recaptcha from google loading. Similar to this a random hash string which we generate in settings or via filter which we later on can setup like this to block: https://www.gulshankumar.net/stop-spam-comments-wordpress/
 
Even if you add a disallowed comment keys it will create an entry in the database and trash them. But what you want it to prevent them from passing through to trash with spam.

But don't you think there is a solution similar to forget spam comment that could work for site reviews submissions to add some hash that would stop them from hitting with spam submissions.

**Comment by pryley** [comment]
I'm not going to implement this.

It's not a solution that will work for all websites (as explained above) so it's not worth the potential support headache. Also this method can easily be bypassed by spam bots using a chromeless browser.

**Comment by wpsumo** [comment]
Most spambots are in my experience simpler, using old HTTP version, not sure if they would go that far and use chromless browser as of today.

Could you just let me know what action is used to submit the reviews? Maybe we can block and restrict here manually upon our own needs. Like comments need /wp-comments.php to submit via the action.

**Comment by pryley** [comment]
Site Reviews uses admin-ajax.php
