### ISSUE TITLE
Viewing Review Filter addon - 404

### ISSUE THREAD

**Issue by ajtruckle** [geminilabs/site-reviews#43]
Hi

I click the link to view more about the Review Filter addon:

![Addon1](https://user-images.githubusercontent.com/7985331/213242180-025cc792-aa1f-4a72-afa3-29176b90ccef.jpg)

But when I click it it comes up with a 404:

![Addon2](https://user-images.githubusercontent.com/7985331/213242296-b17d16e1-70f6-493f-9d9a-270120e7b9f8.jpg)

I tried twice.

Thoughts?

**Comment by ajtruckle** [comment]
It implies that it is a free addon . Since the link does not work, I can't determine how to install it.

**Comment by ajtruckle** [comment]
It seems that the GUI might be out of date because this page:

https://wordpress.org/plugins/site-reviews/#faq

> If you need even more features, [Site Reviews Premium](https://niftyplugins.com/plugins/site-reviews-premium/) gives you access to all of our paid addons, and offers faster and more personalised support.

It's a bit confusing.

**Comment by pryley** [comment]
This is a bug, thanks for reporting it.

In the following code, `{{ link }}` should be `{{ url }}`:

https://github.com/pryley/site-reviews/blob/66e4b469ad19be9541f8c2f3a1f3042571f410a2/views/partials/addons/addon.php#L28

This will be fixed in the next update.

Since Site Reviews v6.4.0, all free addons were merged into the core Site Reviews plugin. All remaining addons are paid addons.

**Comment by ajtruckle** [comment]
OK, I look forward to the updated plugin. If the free addon is merged into the core, I can't work out how to use this particular feature.

**Comment by pryley** [comment]
The Review Filters addon can be found here: https://niftyplugins.com/plugins/site-reviews-filters/

**Comment by pryley** [comment]
Fixed by 720c4362f5619a4e161b8e96da82bf40514d6686

**Comment by ajtruckle** [comment]
Yes, I have seen that page. But there is no way to download that plugin directly? I only see it as paid. But the GUI implies free.

**Comment by pryley** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/134939/213277068-eaa80019-e70c-4623-a845-5645a57fe3b1.png">

**Comment by ajtruckle** [comment]
Yes, just realised that. But, the main Site Review plugin implies this Filters addon is free.

![Addons3](https://user-images.githubusercontent.com/7985331/213277601-2240c6ba-1f4e-477c-93f9-b31992435a89.jpg)

**Comment by pryley** [comment]
The addons are not free. 

The Review Notifications and Review Themes addons say "Premium members only" because they are still in beta. While in beta they cannot be purchased individually and are only available if you have a **Premium** license (the Premium license provides access to all addons).

**Comment by ajtruckle** [comment]
Ok. Now I understand. I thought the first three were free. Understood.
