### ISSUE TITLE
Clarification about using Filter and Form addons

### ISSUE THREAD

**Issue by ajtruckle** [geminilabs/site-reviews#44]
Hi !

My conversion about these started in the Wordpress [support forum](https://wordpress.org/support/topic/categories-332/) but I prefer to chat about it here if you don't mind.

1. I know about **Site Reviews Premium**, but it includes Review Images which I really do not need for this website of mine. I do think that Filter / Form can be used. So is there any possibility of a discount if I purchase these two addons?
2. The **Review Filters** documentation page shows two examples of using shortcodes. But what about when we are using Gutenberg blocks? How does it work in this environment?
3. The same question for **Review Forms**. How do we use it with Gutenberg block?
4. Can the Checklist support multiple items? This is not critical, but a user might want to write about both Meeting Schedule Assistant and Public Talks. Since I have several software applications it would be nice if they could easily indicate which software the review covers.

Thank you.

**Comment by pryley** [comment]
Site Reviews provides blocks (Gutenberg), Elementor widgets, and shortcodes. All official addons integrate with these or provide their own additional blocks, widgets, shortcodes (so they all work with Gutenberg blocks).

The checkbox field in the Review Forms addon supports multiple values, radios support only single values. 

In future, please use the [WordPress Support Forum](https://wordpress.org/support/plugin/site-reviews/) for help with Site Reviews, and the Support Form on your Nifty Plug-ins account for help with the addons. 

If you have pre-purchase questions about the addons, you can use the chat function or [Contact form](https://niftyplugins.com/contact/) on the Nifty Plugins website. Site Reviews Premium is the discounted option for purchasing the addons.

GitHub Issues should only be used to report bugs with Site Reviews, it is not a support channel for the plugin, or for the addons.

Thanks
