### ISSUE TITLE
Template tag review_link deprecated?

### ISSUE THREAD

**Issue by LoganStrike** [geminilabs/site-reviews#45]
In the template for the email notification that gets sent when a new review is submitted and awaiting approval, there used to be a review_link template tag to insert the review's post edit link. It appears that template tag no longer works, and I see there is now an edit_url template tag.

Is the review_link template tag removed from the plugin, or is this a bug?

I can use the edit_url template tag for all sites moving forward, but we have several dozen or possibly 100+ websites that are using the older review_link template tag, so if that tag is no longer available, is there any chance of having the review_link tag automatically swapped out for the edit_url tag and accompanying HTML for the link? I understand if that is not feasible.

Thanks for your time and a great plugin!

**Comment by pryley** [comment]
This will be fixed in version 7.
