### ISSUE TITLE
Use email address from the user profile

### ISSUE THREAD

**Issue by simorxb** [geminilabs/site-reviews#46]
As an improvement, I think it would be nice to use the email address from the user profile when they leave a review.

The review form has the email address field, but when a user is already logged in that information is already known and I think asking the user to re-enter it doesn't help with user experience. I can see two ways (possibly configurable):

1. Leave the field but pre-complete it with the email address
2. Remove the field and use the email address from the user profile

The same could be true for first name and surname.

**Comment by pryley** [comment]
`[site_reviews_form hide="email,name"]` and Site Reviews will automatically use the email and display name of the logged in user.
